Remove venv check
pipxproject/pipx pull request #477
Opened 2020-08-24 19:01 UTC by jonringer

## Summary of changes
venv is available through the standard library since 3.3
https://www.python.org/dev/peps/pep-0405/

## Test plan

Tested by running
```
# command(s) to exercise these changes
```

2020-08-25 12:41 UTC, FRidh commented
If the point is to detect whether we are not in a `virtualenv` environment *and* require we are in a `venv`, then the helper seems correct to me. If the helper does not need to run inside a `venv`, then it can be removed. No idea why it would require being tested inside a `venv`.

The second line tests whether `base_prefix` is unequal to `prefix`. This is the case when you are inside a `venv` environment. To check whether `virtualenv` is used instead of `venv` the first line is used.

In case `base_prefix` is used it falls back to `prefix`, which of course always fails. Thus, the test only functions in Python 3.3 and above (because that's when `base_prefix` was introduced).

https://virtualenv.pypa.io/en/16.7.9/reference.html#compatibility-with-the-stdlib-venv-module

2020-08-25 13:16 UTC, uranusjr commented
Since modern virtualenv implements PEP 405 and is as capable as the built-in venv, maybe the two checks should be reversed to allow tests to be run inside it as well?

2020-08-26 08:08 UTC, gaborbernat requested changes
Yeah, I agree with @uranusjr here.

2020-08-26 08:16 UTC, jonringer commented
In the linked PR, you can see that we don't use virutalenv and we remove the assertion that this PR is all about. We still had to disable tests which touched network. But on the whole, the test suite doesn't need them.

2020-08-26 08:54 UTC, gaborbernat commented
The thing is the test suite can run under virtualenv 20+ though, not?

2020-08-26 16:51 UTC, jonringer commented
Probably? But that's not the point of this PR, which is to remove the inconclusive assertion on venv.

2020-08-26 16:54 UTC, gaborbernat approved these changes

2020-08-26 16:54 UTC, merged