Mention that pipx requires pip 10+ to install
pipxproject/pipx pull request #619
Opened 2021-02-02 07:01 UTC by uranusjr

Technically pipx *can* be installed with earlier pip versions with setuptools 30.3+ and wheel installed, but that description is probably too confusing for most.

2021-02-02 18:22 UTC, tucked approved these changes

2021-02-02 19:11 UTC, itsayellow requested changes
Could you also make the same change in the Install portion of `README.txt` please.

2021-02-03 05:21 UTC, uranusjr commented
Thanks, added.

2021-02-03 06:09 UTC, itsayellow approved these changes
awesome, thanks.

2021-02-24 23:54 UTC, merged